from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import sqlite3
from enum import Enum
from math import *


class Ui_MainWindow(object):
    
    class Operator(Enum):
        Sum = '+',
        Minus = '-',
        Degree = '^',
        Multiply = '*',
        Division = '/'

    operator = None
    number_1 = None
    number_2 = None
    file = open('history.sqlite', 'w')
    file.close()
    connect = sqlite3.connect("./history.sqlite")
    request = connect.cursor()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 416)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(361, 416))
        MainWindow.setMaximumSize(QtCore.QSize(361, 416))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 371, 401))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.buttonDot = QtWidgets.QPushButton(self.tab)
        self.buttonDot.setGeometry(QtCore.QRect(220, 300, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonDot.setFont(font)
        self.buttonDot.setObjectName("buttonDot")
        self.buttonCls = QtWidgets.QPushButton(self.tab)
        self.buttonCls.setGeometry(QtCore.QRect(290, 300, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonCls.setFont(font)
        self.buttonCls.setObjectName("buttonCls")
        self.button_7 = QtWidgets.QPushButton(self.tab)
        self.button_7.setGeometry(QtCore.QRect(10, 230, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_7.setFont(font)
        self.button_7.setObjectName("button_7")
        self.button_9 = QtWidgets.QPushButton(self.tab)
        self.button_9.setGeometry(QtCore.QRect(150, 230, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_9.setFont(font)
        self.button_9.setObjectName("button_9")
        self.buttonEqual = QtWidgets.QPushButton(self.tab)
        self.buttonEqual.setGeometry(QtCore.QRect(150, 300, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonEqual.setFont(font)
        self.buttonEqual.setObjectName("buttonEqual")
        self.button_8 = QtWidgets.QPushButton(self.tab)
        self.button_8.setGeometry(QtCore.QRect(80, 230, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_8.setFont(font)
        self.button_8.setObjectName("button_8")
        self.button_3 = QtWidgets.QPushButton(self.tab)
        self.button_3.setGeometry(QtCore.QRect(150, 90, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_3.setFont(font)
        self.button_3.setObjectName("button_3")
        self.button_4 = QtWidgets.QPushButton(self.tab)
        self.button_4.setGeometry(QtCore.QRect(10, 160, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_4.setFont(font)
        self.button_4.setObjectName("button_4")
        self.buttonDegree = QtWidgets.QPushButton(self.tab)
        self.buttonDegree.setGeometry(QtCore.QRect(220, 90, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonDegree.setFont(font)
        self.buttonDegree.setObjectName("buttonDegree")
        self.button_2 = QtWidgets.QPushButton(self.tab)
        self.button_2.setGeometry(QtCore.QRect(80, 90, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_2.setFont(font)
        self.button_2.setObjectName("button_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 0, 341, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.buttonMul = QtWidgets.QPushButton(self.tab)
        self.buttonMul.setGeometry(QtCore.QRect(220, 230, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonMul.setFont(font)
        self.buttonMul.setObjectName("buttonMul")
        self.button_5 = QtWidgets.QPushButton(self.tab)
        self.button_5.setGeometry(QtCore.QRect(80, 160, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_5.setFont(font)
        self.button_5.setObjectName("button_5")
        self.buttonRoot = QtWidgets.QPushButton(self.tab)
        self.buttonRoot.setGeometry(QtCore.QRect(290, 90, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonRoot.setFont(font)
        self.buttonRoot.setObjectName("buttonRoot")
        self.button_1 = QtWidgets.QPushButton(self.tab)
        self.button_1.setGeometry(QtCore.QRect(10, 90, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_1.setFont(font)
        self.button_1.setObjectName("button_1")
        self.button_6 = QtWidgets.QPushButton(self.tab)
        self.button_6.setGeometry(QtCore.QRect(150, 160, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_6.setFont(font)
        self.button_6.setObjectName("button_6")
        self.button_0 = QtWidgets.QPushButton(self.tab)
        self.button_0.setGeometry(QtCore.QRect(10, 300, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_0.setFont(font)
        self.button_0.setObjectName("button_0")
        self.buttonMinus = QtWidgets.QPushButton(self.tab)
        self.buttonMinus.setGeometry(QtCore.QRect(220, 160, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonMinus.setFont(font)
        self.buttonMinus.setObjectName("buttonMinus")
        self.buttonDiv = QtWidgets.QPushButton(self.tab)
        self.buttonDiv.setGeometry(QtCore.QRect(290, 230, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonDiv.setFont(font)
        self.buttonDiv.setObjectName("buttonDiv")
        self.buttonSum = QtWidgets.QPushButton(self.tab)
        self.buttonSum.setGeometry(QtCore.QRect(290, 160, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonSum.setFont(font)
        self.buttonSum.setObjectName("buttonSum")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.buttonCls_all = QtWidgets.QPushButton(self.tab_2)
        self.buttonCls_all.setGeometry(QtCore.QRect(310, 320, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonCls_all.setFont(font)
        self.buttonCls_all.setObjectName("buttonCls_all")
        self.buttonIn_7 = QtWidgets.QPushButton(self.tab_2)
        self.buttonIn_7.setGeometry(QtCore.QRect(110, 270, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonIn_7.setFont(font)
        self.buttonIn_7.setObjectName("buttonIn_7")
        self.buttonIn_9 = QtWidgets.QPushButton(self.tab_2)
        self.buttonIn_9.setGeometry(QtCore.QRect(210, 270, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonIn_9.setFont(font)
        self.buttonIn_9.setObjectName("buttonIn_9")
        self.buttonEqual_2 = QtWidgets.QPushButton(self.tab_2)
        self.buttonEqual_2.setGeometry(QtCore.QRect(210, 320, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.buttonEqual_2.setFont(font)
        self.buttonEqual_2.setObjectName("buttonEqual_2")
        self.buttonIn_8 = QtWidgets.QPushButton(self.tab_2)
        self.buttonIn_8.setGeometry(QtCore.QRect(160, 270, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonIn_8.setFont(font)
        self.buttonIn_8.setObjectName("buttonIn_8")
        self.buttonIn_3 = QtWidgets.QPushButton(self.tab_2)
        self.buttonIn_3.setGeometry(QtCore.QRect(210, 170, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonIn_3.setFont(font)
        self.buttonIn_3.setObjectName("buttonIn_3")
        self.buttonIn_4 = QtWidgets.QPushButton(self.tab_2)
        self.buttonIn_4.setGeometry(QtCore.QRect(110, 220, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonIn_4.setFont(font)
        self.buttonIn_4.setObjectName("buttonIn_4")
        self.buttonDegree_2 = QtWidgets.QPushButton(self.tab_2)
        self.buttonDegree_2.setGeometry(QtCore.QRect(260, 120, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonDegree_2.setFont(font)
        self.buttonDegree_2.setObjectName("buttonDegree_2")
        self.buttonIn_2 = QtWidgets.QPushButton(self.tab_2)
        self.buttonIn_2.setGeometry(QtCore.QRect(160, 170, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonIn_2.setFont(font)
        self.buttonIn_2.setObjectName("buttonIn_2")
        self.textArea = QtWidgets.QLabel(self.tab_2)
        self.textArea.setGeometry(QtCore.QRect(0, 50, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.textArea.setFont(font)
        self.textArea.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textArea.setObjectName("textArea")
        self.buttonMul_2 = QtWidgets.QPushButton(self.tab_2)
        self.buttonMul_2.setGeometry(QtCore.QRect(260, 270, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonMul_2.setFont(font)
        self.buttonMul_2.setObjectName("buttonMul_2")
        self.buttonIn_5 = QtWidgets.QPushButton(self.tab_2)
        self.buttonIn_5.setGeometry(QtCore.QRect(160, 220, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonIn_5.setFont(font)
        self.buttonIn_5.setObjectName("buttonIn_5")
        self.buttonRoot_2 = QtWidgets.QPushButton(self.tab_2)
        self.buttonRoot_2.setGeometry(QtCore.QRect(310, 120, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonRoot_2.setFont(font)
        self.buttonRoot_2.setObjectName("buttonRoot_2")
        self.buttonIn_1 = QtWidgets.QPushButton(self.tab_2)
        self.buttonIn_1.setGeometry(QtCore.QRect(110, 170, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonIn_1.setFont(font)
        self.buttonIn_1.setObjectName("buttonIn_1")
        self.buttonIn_6 = QtWidgets.QPushButton(self.tab_2)
        self.buttonIn_6.setGeometry(QtCore.QRect(210, 220, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonIn_6.setFont(font)
        self.buttonIn_6.setObjectName("buttonIn_6")
        self.buttonIn_0 = QtWidgets.QPushButton(self.tab_2)
        self.buttonIn_0.setGeometry(QtCore.QRect(110, 320, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonIn_0.setFont(font)
        self.buttonIn_0.setObjectName("buttonIn_0")
        self.buttonDot_2 = QtWidgets.QPushButton(self.tab_2)
        self.buttonDot_2.setGeometry(QtCore.QRect(260, 170, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonDot_2.setFont(font)
        self.buttonDot_2.setObjectName("buttonDot_2")
        self.buttonMinus_2 = QtWidgets.QPushButton(self.tab_2)
        self.buttonMinus_2.setGeometry(QtCore.QRect(260, 220, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonMinus_2.setFont(font)
        self.buttonMinus_2.setObjectName("buttonMinus_2")
        self.buttonDiv_2 = QtWidgets.QPushButton(self.tab_2)
        self.buttonDiv_2.setGeometry(QtCore.QRect(310, 220, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonDiv_2.setFont(font)
        self.buttonDiv_2.setObjectName("buttonDiv_2")
        self.buttonSum_2 = QtWidgets.QPushButton(self.tab_2)
        self.buttonSum_2.setGeometry(QtCore.QRect(310, 170, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonSum_2.setFont(font)
        self.buttonSum_2.setObjectName("buttonSum_2")
        self.history = QtWidgets.QLabel(self.tab_2)
        self.history.setGeometry(QtCore.QRect(0, 0, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.history.setFont(font)
        self.history.setStyleSheet("QPushButton {\n"
"    color: rgba(255, 255, 255, 0.5);\n"
"}")
        self.history.setText("")
        self.history.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.history.setObjectName("history")
        self.buttonCls_textArea = QtWidgets.QPushButton(self.tab_2)
        self.buttonCls_textArea.setGeometry(QtCore.QRect(310, 270, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonCls_textArea.setFont(font)
        self.buttonCls_textArea.setObjectName("buttonCls_textArea")
        self.buttonFact = QtWidgets.QPushButton(self.tab_2)
        self.buttonFact.setGeometry(QtCore.QRect(60, 320, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonFact.setFont(font)
        self.buttonFact.setObjectName("buttonFact")
        self.buttonRightBr = QtWidgets.QPushButton(self.tab_2)
        self.buttonRightBr.setGeometry(QtCore.QRect(210, 120, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonRightBr.setFont(font)
        self.buttonRightBr.setObjectName("buttonRightBr")
        self.buttonLeftBr = QtWidgets.QPushButton(self.tab_2)
        self.buttonLeftBr.setGeometry(QtCore.QRect(160, 120, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonLeftBr.setFont(font)
        self.buttonLeftBr.setObjectName("buttonLeftBr")
        self.buttonSigned = QtWidgets.QPushButton(self.tab_2)
        self.buttonSigned.setGeometry(QtCore.QRect(60, 270, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonSigned.setFont(font)
        self.buttonSigned.setObjectName("buttonSigned")
        self.buttonLog = QtWidgets.QPushButton(self.tab_2)
        self.buttonLog.setGeometry(QtCore.QRect(60, 120, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonLog.setFont(font)
        self.buttonLog.setObjectName("buttonLog")
        self.buttonSin = QtWidgets.QPushButton(self.tab_2)
        self.buttonSin.setGeometry(QtCore.QRect(10, 170, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonSin.setFont(font)
        self.buttonSin.setObjectName("buttonSin")
        self.buttonCos = QtWidgets.QPushButton(self.tab_2)
        self.buttonCos.setGeometry(QtCore.QRect(10, 220, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonCos.setFont(font)
        self.buttonCos.setObjectName("buttonCos")
        self.buttonTg = QtWidgets.QPushButton(self.tab_2)
        self.buttonTg.setGeometry(QtCore.QRect(10, 270, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonTg.setFont(font)
        self.buttonTg.setObjectName("buttonTg")
        self.buttonCtg = QtWidgets.QPushButton(self.tab_2)
        self.buttonCtg.setGeometry(QtCore.QRect(10, 320, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonCtg.setFont(font)
        self.buttonCtg.setObjectName("buttonCtg")
        self.buttonLn = QtWidgets.QPushButton(self.tab_2)
        self.buttonLn.setGeometry(QtCore.QRect(10, 120, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonLn.setFont(font)
        self.buttonLn.setObjectName("buttonLn")
        self.buttonUnsigned = QtWidgets.QPushButton(self.tab_2)
        self.buttonUnsigned.setGeometry(QtCore.QRect(110, 120, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonUnsigned.setFont(font)
        self.buttonUnsigned.setObjectName("buttonUnsigned")
        self.buttonP = QtWidgets.QPushButton(self.tab_2)
        self.buttonP.setGeometry(QtCore.QRect(60, 220, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonP.setFont(font)
        self.buttonP.setObjectName("buttonP")
        self.buttonE = QtWidgets.QPushButton(self.tab_2)
        self.buttonE.setGeometry(QtCore.QRect(60, 170, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonE.setFont(font)
        self.buttonE.setObjectName("buttonE")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formul = QtWidgets.QLabel(self.tab_3)
        self.formul.setGeometry(QtCore.QRect(0, 0, 351, 71))
        self.formul.setAlignment(QtCore.Qt.AlignCenter)
        self.formul.setObjectName("formul")
        self.formul_1 = QtWidgets.QPushButton(self.tab_3)
        self.formul_1.setGeometry(QtCore.QRect(10, 100, 161, 31))
        self.formul_1.setObjectName("formul_1")
        self.formul_2 = QtWidgets.QPushButton(self.tab_3)
        self.formul_2.setGeometry(QtCore.QRect(190, 100, 161, 31))
        self.formul_2.setObjectName("formul_2")
        self.formul_3 = QtWidgets.QPushButton(self.tab_3)
        self.formul_3.setGeometry(QtCore.QRect(10, 170, 161, 31))
        self.formul_3.setObjectName("formul_3")
        self.formul_5 = QtWidgets.QPushButton(self.tab_3)
        self.formul_5.setGeometry(QtCore.QRect(10, 240, 161, 31))
        self.formul_5.setObjectName("formul_5")
        self.formul_4 = QtWidgets.QPushButton(self.tab_3)
        self.formul_4.setGeometry(QtCore.QRect(190, 170, 161, 31))
        self.formul_4.setObjectName("formul_4")
        self.formul_6 = QtWidgets.QPushButton(self.tab_3)
        self.formul_6.setGeometry(QtCore.QRect(190, 240, 161, 31))
        self.formul_6.setObjectName("formul_6")
        self.formul_7 = QtWidgets.QPushButton(self.tab_3)
        self.formul_7.setGeometry(QtCore.QRect(10, 310, 161, 31))
        self.formul_7.setObjectName("formul_7")
        self.formul_8 = QtWidgets.QPushButton(self.tab_3)
        self.formul_8.setGeometry(QtCore.QRect(190, 310, 161, 31))
        self.formul_8.setObjectName("formul_8")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setEnabled(True)
        self.tab_4.setObjectName("tab_4")
        self.label_2 = QtWidgets.QLabel(self.tab_4)
        self.label_2.setGeometry(QtCore.QRect(-4, 2, 361, 61))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.common()
        self.engineere()
        self.math()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonDot.setText(_translate("MainWindow", "."))
        self.buttonCls.setText(_translate("MainWindow", "CE"))
        self.button_7.setText(_translate("MainWindow", "7"))
        self.button_9.setText(_translate("MainWindow", "9"))
        self.buttonEqual.setText(_translate("MainWindow", "="))
        self.button_8.setText(_translate("MainWindow", "8"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.button_4.setText(_translate("MainWindow", "4"))
        self.buttonDegree.setText(_translate("MainWindow", "x^n"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.label.setText(_translate("MainWindow", "0"))
        self.buttonMul.setText(_translate("MainWindow", "*"))
        self.button_5.setText(_translate("MainWindow", "5"))
        self.buttonRoot.setText(_translate("MainWindow", "√"))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_6.setText(_translate("MainWindow", "6"))
        self.button_0.setText(_translate("MainWindow", "0"))
        self.buttonMinus.setText(_translate("MainWindow", "-"))
        self.buttonDiv.setText(_translate("MainWindow", "/"))
        self.buttonSum.setText(_translate("MainWindow", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Common"))
        self.buttonCls_all.setText(_translate("MainWindow", "CE"))
        self.buttonIn_7.setText(_translate("MainWindow", "7"))
        self.buttonIn_9.setText(_translate("MainWindow", "9"))
        self.buttonEqual_2.setText(_translate("MainWindow", "="))
        self.buttonIn_8.setText(_translate("MainWindow", "8"))
        self.buttonIn_3.setText(_translate("MainWindow", "3"))
        self.buttonIn_4.setText(_translate("MainWindow", "4"))
        self.buttonDegree_2.setText(_translate("MainWindow", "x^n"))
        self.buttonIn_2.setText(_translate("MainWindow", "2"))
        self.textArea.setText(_translate("MainWindow", "0"))
        self.buttonMul_2.setText(_translate("MainWindow", "*"))
        self.buttonIn_5.setText(_translate("MainWindow", "5"))
        self.buttonRoot_2.setText(_translate("MainWindow", "√"))
        self.buttonIn_1.setText(_translate("MainWindow", "1"))
        self.buttonIn_6.setText(_translate("MainWindow", "6"))
        self.buttonIn_0.setText(_translate("MainWindow", "0"))
        self.buttonDot_2.setText(_translate("MainWindow", "."))
        self.buttonMinus_2.setText(_translate("MainWindow", "-"))
        self.buttonDiv_2.setText(_translate("MainWindow", "/"))
        self.buttonSum_2.setText(_translate("MainWindow", "+"))
        self.buttonCls_textArea.setText(_translate("MainWindow", "C"))
        self.buttonFact.setText(_translate("MainWindow", "!"))
        self.buttonRightBr.setText(_translate("MainWindow", ")"))
        self.buttonLeftBr.setText(_translate("MainWindow", "("))
        self.buttonSigned.setText(_translate("MainWindow", "+/-"))
        self.buttonLog.setText(_translate("MainWindow", "log"))
        self.buttonSin.setText(_translate("MainWindow", "sin"))
        self.buttonCos.setText(_translate("MainWindow", "cos"))
        self.buttonTg.setText(_translate("MainWindow", "tg"))
        self.buttonCtg.setText(_translate("MainWindow", "ctg"))
        self.buttonLn.setText(_translate("MainWindow", "ln"))
        self.buttonUnsigned.setText(_translate("MainWindow", "|x|"))
        self.buttonP.setText(_translate("MainWindow", "π"))
        self.buttonE.setText(_translate("MainWindow", "e"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Engineering"))
        self.formul.setText(_translate("MainWindow", ""))
        self.formul_1.setText(_translate("MainWindow", "Sum squared"))
        self.formul_2.setText(_translate("MainWindow", "Difference squared"))
        self.formul_3.setText(_translate("MainWindow", "Sum of squares"))
        self.formul_5.setText(_translate("MainWindow", "Sum cube"))
        self.formul_4.setText(_translate("MainWindow", "Difference of squares"))
        self.formul_6.setText(_translate("MainWindow", "Difference cube"))
        self.formul_7.setText(_translate("MainWindow", "Sum of cubes"))
        self.formul_8.setText(_translate("MainWindow", "Difference of cubes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Mathic"))
        self.label_2.setText(_translate("MainWindow", "Made by VladiSlave Contact: fakegmail@gmail.com"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Contact"))

    def common(self):
        self.button_0.clicked.connect(lambda: self.labelTextChange(self.label, self.button_0.text()))
        self.button_1.clicked.connect(lambda: self.labelTextChange(self.label, self.button_1.text()))
        self.button_2.clicked.connect(lambda: self.labelTextChange(self.label, self.button_2.text()))
        self.button_3.clicked.connect(lambda: self.labelTextChange(self.label, self.button_3.text()))
        self.button_4.clicked.connect(lambda: self.labelTextChange(self.label, self.button_4.text()))
        self.button_5.clicked.connect(lambda: self.labelTextChange(self.label, self.button_5.text()))
        self.button_6.clicked.connect(lambda: self.labelTextChange(self.label, self.button_6.text()))
        self.button_7.clicked.connect(lambda: self.labelTextChange(self.label, self.button_7.text()))
        self.button_8.clicked.connect(lambda: self.labelTextChange(self.label, self.button_8.text()))
        self.button_9.clicked.connect(lambda: self.labelTextChange(self.label, self.button_9.text()))
        self.buttonDot.clicked.connect(lambda: self.specTextChange(self.label, self.buttonDot.text()))
        self.buttonSum.clicked.connect(lambda: self.setOperator(self.Operator.Sum))
        self.buttonMinus.clicked.connect(lambda: self.setOperator(self.Operator.Minus))
        self.buttonMul.clicked.connect(lambda: self.setOperator(self.Operator.Multiply))
        self.buttonDiv.clicked.connect(lambda: self.setOperator(self.Operator.Division))
        self.buttonRoot.clicked.connect(lambda: self.rootResult())
        self.buttonDegree.clicked.connect(lambda: self.setOperator(self.Operator.Degree))
        self.buttonEqual.clicked.connect(lambda: self.result())
        self.buttonCls.clicked.connect(lambda: self.clear())

    def setOperator(self, operation): 
        self.operator = operation
        self.number_1 = float(self.label.text())
        self.label.setText("")

    def rootResult(self):
        if self.number_1 == 0:
            return 
        self.number_1 = float(self.label.text())
        self.number_1 = float('{:.3f}'.format(sqrt(self.number_1)))
        self.label.setText(str(self.number_1))
        self.request.execute('''CREATE TABLE IF NOT EXISTS calc (operation TEXT);''')
        self.request.execute(f"""INSERT INTO calc (operation) VALUES ('{str(self.number_1)}√={self.label.text()}')""")
        self.connect.commit()

    def result(self):
        if self.number_1 == 0 and self.number_2 == 0:
            return 
        self.number_2 = float(self.label.text())
        match self.operator:
            case self.Operator.Sum: self.label.setText(str(self.number_1 + self.number_2))
            case self.Operator.Minus: self.label.setText(str(self.number_1 - self.number_2))
            case self.Operator.Division: self.label.setText(str(self.number_1 / self.number_2))
            case self.Operator.Multiply: self.label.setText(str(self.number_1 * self.number_2))
            case self.Operator.Degree: self.label.setText(str(self.number_1 ** self.number_2))
            case _: return
        self.request.execute('''CREATE TABLE IF NOT EXISTS calc (operation TEXT);''')
        self.request.execute(f"""INSERT INTO calc (operation) VALUES ('{str(self.number_1)}{self.operator.value[0]}{str(self.number_2)}={self.label.text()}')""")
        self.connect.commit()

    def labelTextChange(self, label, number):
        if self.history.text().find('=') > 0:
            label.setText("")
            self.history.setText("")
        if label.text() == "0":
            label.setText(label.text()[1:])
        label.setText(label.text() + number)

    def specTextChange(self, label, symbol):
        if label.text().find(symbol) < 0 and label.text() != "":
            label.setText(label.text() + symbol)

    def clear(self):
        self.label.setText("")
        self.number_1 = None
        self.number_2 = None

    def transfer(self, from_, into_, symbol):
        if from_.text() != "" and into_.text() != "" and self.history.text().find("=") > 0:
            into_.setText("")
        if from_.text() != "" and from_.text()[-1] != "." or into_.text() != "" and into_.text()[-1] != "+" and into_.text()[-1] != "-" \
            and into_.text()[-1] != "*" and into_.text()[-1] != "/":
            into_.setText(into_.text() + from_.text() + symbol)
        from_.setText("")

    def specTransfer(self, from_, into_, str):
        if from_.text() != "" and into_.text().find("=") < 0 and from_.text()[-1] != "(" and from_.text()[-1] != ")":
            into_.setText(into_.text() + f"{str}({from_.text()})")
            from_.setText("")

    def specResult(self):
        try:
                if self.history.text() != "" and self.history.text()[-1] != "+" and self.history.text()[-1] != "-" and self.history.text()[-1] != "*" \
                and self.history.text()[-1] != "*" and self.history.text().find("=") < 0 or self.history.text().find("=") < 0 and self.textArea.text() != "":
                    self.history.setText(self.history.text() + self.textArea.text())
                    self.textArea.setText(str(float('{:.3f}'.format(eval(self.history.text())))))
                    self.history.setText(self.history.text() + '=' + str(float('{:.3f}'.format(eval(self.history.text())))))
        except Exception as error:
            print(f"Error: {error}")

    def signedCheck(self, label):
        if len(label.text()) > 0 and label.text()[0] == '-':
            label.setText(label.text()[1:])
        elif len(label.text()) > 0:
            label.setText('-' + label.text())

    def changeValues(self, value):
        self.textArea.setText(value)

    def cleanArea(self, label_1, label_2 = ""):
        label_1.setText("")
        if label_2 != "": label_2.setText("")

    def engineere(self):
        self.buttonIn_0.clicked.connect(lambda: self.labelTextChange(self.textArea, self.buttonIn_0.text()))
        self.buttonIn_1.clicked.connect(lambda: self.labelTextChange(self.textArea, self.buttonIn_1.text()))
        self.buttonIn_2.clicked.connect(lambda: self.labelTextChange(self.textArea, self.buttonIn_2.text()))
        self.buttonIn_3.clicked.connect(lambda: self.labelTextChange(self.textArea, self.buttonIn_3.text()))
        self.buttonIn_4.clicked.connect(lambda: self.labelTextChange(self.textArea, self.buttonIn_4.text()))
        self.buttonIn_5.clicked.connect(lambda: self.labelTextChange(self.textArea, self.buttonIn_5.text()))
        self.buttonIn_6.clicked.connect(lambda: self.labelTextChange(self.textArea, self.buttonIn_6.text()))
        self.buttonIn_7.clicked.connect(lambda: self.labelTextChange(self.textArea, self.buttonIn_7.text()))
        self.buttonIn_8.clicked.connect(lambda: self.labelTextChange(self.textArea, self.buttonIn_8.text()))
        self.buttonIn_9.clicked.connect(lambda: self.labelTextChange(self.textArea, self.buttonIn_9.text()))
        self.buttonRightBr.clicked.connect(lambda: self.labelTextChange(self.textArea, self.buttonRightBr.text()))
        self.buttonLeftBr.clicked.connect(lambda: self.labelTextChange(self.textArea, self.buttonLeftBr.text()))
        self.buttonDot_2.clicked.connect(lambda: self.specTextChange(self.textArea, self.buttonDot_2.text()))
        self.buttonMinus_2.clicked.connect(lambda: self.transfer(self.textArea, self.history, self.buttonMinus_2.text()))
        self.buttonSum_2.clicked.connect(lambda: self.transfer(self.textArea, self.history, self.buttonSum_2.text()))
        self.buttonMul_2.clicked.connect(lambda: self.transfer(self.textArea, self.history, self.buttonMul_2.text()))
        self.buttonDiv_2.clicked.connect(lambda: self.transfer(self.textArea, self.history, self.buttonDiv_2.text()))
        self.buttonDegree_2.clicked.connect(lambda: self.transfer(self.textArea, self.history, "**"))
        self.buttonFact.clicked.connect(lambda: self.specTransfer(self.textArea, self.history, "factorial"))
        self.buttonCos.clicked.connect(lambda: self.specTransfer(self.textArea, self.history, "cos"))
        self.buttonSin.clicked.connect(lambda: self.specTransfer(self.textArea, self.history, "sin"))
        self.buttonTg.clicked.connect(lambda: self.specTransfer(self.textArea, self.history, "tan"))
        self.buttonCtg.clicked.connect(lambda: self.specTransfer(self.textArea, self.history, "1 / ctg"))
        self.buttonUnsigned.clicked.connect(lambda: self.specTransfer(self.textArea, self.history, "abs"))
        self.buttonSigned.clicked.connect(lambda: self.signedCheck(self.textArea))
        self.buttonLog.clicked.connect(lambda: self.specTransfer(self.textArea, self.history, "log"))
        self.buttonLn.clicked.connect(lambda: self.specTransfer(self.textArea, self.history, "log10"))
        self.buttonRoot_2.clicked.connect(lambda: self.specTransfer(self.textArea, self.history, "sqrt"))
        self.buttonE.clicked.connect(lambda: self.changeValues("2.718"))
        self.buttonP.clicked.connect(lambda: self.changeValues("3.14"))
        self.buttonCls_textArea.clicked.connect(lambda: self.cleanArea(self.textArea))
        self.buttonCls_all.clicked.connect(lambda: self.cleanArea(self.textArea, self.history))
        self.buttonEqual_2.clicked.connect(lambda: self.specResult())

    def outputFormul(self, formul):
        self.formul.setText(formul)

    def math(self):
        self.formul_1.clicked.connect(lambda: self.outputFormul("(a + b)<sup>2</sup> = a<sup>2</sup> + 2ab + b<sup>2</sup>"))
        self.formul_2.clicked.connect(lambda: self.outputFormul("(a - b)<sup>2</sup> = a<sup>2</sup> - 2ab + b<sup>2</sup>"))
        self.formul_3.clicked.connect(lambda: self.outputFormul("a<sup>2</sup> + b<sup>2</sup> = (a + b) * (a + b)"))
        self.formul_4.clicked.connect(lambda: self.outputFormul("a<sup>2</sup> – b<sup>2</sup> = (a + b) * (a - b)"))
        self.formul_5.clicked.connect(lambda: self.outputFormul("(a + b)<sup>3</sup> = a<sup>3</sup> + 3a<sup>2</sup>b + 3ab<sup>2</sup> + b<sup>3</sup>"))
        self.formul_6.clicked.connect(lambda: self.outputFormul("(a - b)<sup>3</sup> = a<sup>3</sup> - 3a<sup>2</sup>b + 3ab<sup>2</sup> - b<sup>3</sup>"))
        self.formul_7.clicked.connect(lambda: self.outputFormul("a<sup>3</sup> + b<sup>3</sup> = (a + b) * (a<sup>2</sup> - ab + b<sup>2</sup>)"))
        self.formul_8.clicked.connect(lambda: self.outputFormul("a<sup>3</sup> - b<sup>3</sup> = (a - b) * (a<sup>2</sup> + ab + b<sup>2</sup>)"))

app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()
sys.exit(app.exec_())